### ISSUE TITLE
Add the DeepDDS model

### ISSUE THREAD

**Issue by cthoyt** [AstraZeneca/chemicalx#19]
- Please read the paper first. It is [here](https://arxiv.org/abs/2107.02467).
- There is also code-release with the paper [here](https://github.com/Sinwang404/DeepDDs).
- After that read the contributing guidelines.
- If there is an existing open-source version of the model please take a look.
- ChemicalX is built on top of [PyTorch 1.10.](https://pytorch.org/) and [torchdrug](https://torchdrug.ai/).
- The library heavily builds on top on [torchdrug](https://torchdrug.ai/) and molecules in batches are PackedGraphs.
- There is already a model class under `./chemicalx/models/`
- Context features, drug level features, and labels are all FloatTensors.
- Look at the examples and tests under `./examples/` and `./tests/`.
- Add auxiliary layers as you see fit - please document these, add tests, and add these layers to the main readme.md if needed.
- Add typing to the initialization and forward pass.
- Non-data-dependent hyper-ammeters should have default values. 
- Please add tests under `./tests/` and make sure that your model/layer is tested with real data.
- Write an example under `./examples/`. What is the AUC on the test set? Is it reasonable?

**Comment by benedekrozemberczki** [comment]
Gavin

**Comment by cthoyt** [comment]
@kkaris?

**Comment by benedekrozemberczki** [comment]
This paper is easier - what do you think @cthoyt ?

**Comment by cthoyt** [comment]
I think it would be better to give Klas the easier one :)

**Comment by benedekrozemberczki** [comment]
Okay, let me switch around in a moment.
