### ISSUE TITLE
Code quality assurance

### ISSUE THREAD

**Issue by cthoyt** [AstraZeneca/chemicalx#25]
Add black, flake8, isort, etc. code quality assurance. This will be very important if/when other people start contributing.

**Comment by benedekrozemberczki** [comment]
Yes, agree. The torch-scatter installation was creating errors with the reformatting step in devops.

**Comment by benedekrozemberczki** [comment]
No worries.

**Comment by benedekrozemberczki** [comment]
Should I modify the Devops pipeline?
