### ISSUE TITLE
Add the DDI Dataset from DeepDDI

### ISSUE THREAD

**Issue by benedekrozemberczki** [AstraZeneca/chemicalx#28]
The triples are here [Dataset](https://bitbucket.org/kaistsystemsbiology/deepddi/src/master/data/KnownDDI.csv).

**Comment by cthoyt** [comment]
For the next dataset we add, I think it would be pretty important to include the preprocessing pipeline as well (e.g., using `pystow` to reproducibly download the data from its source)

Also for this one, I wonder if it's derived from DrugBank, and if we could re-write the pipeline ourselves using `drugbank_downloader` for preparing the dataset
