### ISSUE TITLE
Contribution guide - forking and ssh needed

### ISSUE THREAD

**Issue by bgyori** [AstraZeneca/chemicalx#9]
In the contribution guide, we have
```
2. Clone this repo
git clone https://github.com/AstraZeneca/chemicalx
```
however, people won't generally have permission to push branches to `AstraZeneca/chemicalx` directly. Instead, I think we should describe that users should first fork the repository, then push to a new branch on their fork, and then pull request to `AstraZeneca/chemicalx`. Another issue is that for the push to work, I think ssh instead of https should be used when cloning. Shall I update the guidelines according to the above?

**Comment by benedekrozemberczki** [comment]
Yes please!
