### ISSUE TITLE
ChemicalX Tutorials are not working

### ISSUE THREAD

**Issue by RetrosynthesisAI** [AstraZeneca/chemicalx#90]
The tutorial code here is not working, can you fix it? Also do you have any Jupyter notebooks coming up or available soon?

Tutorials with code that doesn't work
https://chemicalx.readthedocs.io/en/latest/notes/tutorial.html

**Comment by kajocina** [comment]
Can you provide some additional details about the problem? Which part doesn't work and what's the error message? Thanks

**Comment by benedekrozemberczki** [comment]
Fixed it.

**Comment by benedekrozemberczki** [comment]
@RetrosynthesisAI Can you star the repo?

**Comment by RetrosynthesisAI** [comment]
Sure, just did. Thank you!
Margaret
