### ISSUE TITLE
'LabeledTriples' object is not iterable

### ISSUE THREAD

**Issue by aminemosbah** [AstraZeneca/chemicalx#93]
got an error when trying to reproduce the snippet in the parper 
line 14 prediction = model(batch.context_features,batch.drug_features_left,batch.drug_features_right)

TypeError: 'LabeledTriples' object is not iterable]()

**Comment by benedekrozemberczki** [comment]
Can you take a look at the latest version of the paper? Can you also star the repo?

**Comment by aminemosbah** [comment]
i have used the snippet in publication; would you please point me to the last version of the paper 
thx?
